# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karps/proto/io.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karps.proto import types_pb2 as karps_dot_proto_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karps/proto/io.proto',
  package='karps.core',
  syntax='proto3',
  serialized_pb=_b('\n\x14karps/proto/io.proto\x12\nkarps.core\x1a\x17karps/proto/types.proto\"\x1b\n\x0cResourcePath\x12\x0b\n\x03uri\x18\x01 \x01(\t\"\x1d\n\rResourceStamp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x8f\x01\n\x11SourceDescription\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12#\n\x06schema\x18\x03 \x01(\x0b\x32\x13.karps.core.SQLType\x12(\n\x07options\x18\x04 \x03(\x0b\x32\x17.karps.core.InputOption\x12\r\n\x05stamp\x18\x05 \x01(\t\"~\n\x0bInputOption\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x42\x07\n\x05valueb\x06proto3')
  ,
  dependencies=[karps_dot_proto_dot_types__pb2.DESCRIPTOR,])




_RESOURCEPATH = _descriptor.Descriptor(
  name='ResourcePath',
  full_name='karps.core.ResourcePath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='karps.core.ResourcePath.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=88,
)


_RESOURCESTAMP = _descriptor.Descriptor(
  name='ResourceStamp',
  full_name='karps.core.ResourceStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='karps.core.ResourceStamp.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=119,
)


_SOURCEDESCRIPTION = _descriptor.Descriptor(
  name='SourceDescription',
  full_name='karps.core.SourceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='karps.core.SourceDescription.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='karps.core.SourceDescription.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='karps.core.SourceDescription.schema', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='karps.core.SourceDescription.options', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='karps.core.SourceDescription.stamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=265,
)


_INPUTOPTION = _descriptor.Descriptor(
  name='InputOption',
  full_name='karps.core.InputOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='karps.core.InputOption.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='karps.core.InputOption.int_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='karps.core.InputOption.double_value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='karps.core.InputOption.string_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='karps.core.InputOption.bool_value', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='karps.core.InputOption.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=267,
  serialized_end=393,
)

_SOURCEDESCRIPTION.fields_by_name['schema'].message_type = karps_dot_proto_dot_types__pb2._SQLTYPE
_SOURCEDESCRIPTION.fields_by_name['options'].message_type = _INPUTOPTION
_INPUTOPTION.oneofs_by_name['value'].fields.append(
  _INPUTOPTION.fields_by_name['int_value'])
_INPUTOPTION.fields_by_name['int_value'].containing_oneof = _INPUTOPTION.oneofs_by_name['value']
_INPUTOPTION.oneofs_by_name['value'].fields.append(
  _INPUTOPTION.fields_by_name['double_value'])
_INPUTOPTION.fields_by_name['double_value'].containing_oneof = _INPUTOPTION.oneofs_by_name['value']
_INPUTOPTION.oneofs_by_name['value'].fields.append(
  _INPUTOPTION.fields_by_name['string_value'])
_INPUTOPTION.fields_by_name['string_value'].containing_oneof = _INPUTOPTION.oneofs_by_name['value']
_INPUTOPTION.oneofs_by_name['value'].fields.append(
  _INPUTOPTION.fields_by_name['bool_value'])
_INPUTOPTION.fields_by_name['bool_value'].containing_oneof = _INPUTOPTION.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['ResourcePath'] = _RESOURCEPATH
DESCRIPTOR.message_types_by_name['ResourceStamp'] = _RESOURCESTAMP
DESCRIPTOR.message_types_by_name['SourceDescription'] = _SOURCEDESCRIPTION
DESCRIPTOR.message_types_by_name['InputOption'] = _INPUTOPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourcePath = _reflection.GeneratedProtocolMessageType('ResourcePath', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEPATH,
  __module__ = 'karps.proto.io_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ResourcePath)
  ))
_sym_db.RegisterMessage(ResourcePath)

ResourceStamp = _reflection.GeneratedProtocolMessageType('ResourceStamp', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCESTAMP,
  __module__ = 'karps.proto.io_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ResourceStamp)
  ))
_sym_db.RegisterMessage(ResourceStamp)

SourceDescription = _reflection.GeneratedProtocolMessageType('SourceDescription', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEDESCRIPTION,
  __module__ = 'karps.proto.io_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.SourceDescription)
  ))
_sym_db.RegisterMessage(SourceDescription)

InputOption = _reflection.GeneratedProtocolMessageType('InputOption', (_message.Message,), dict(
  DESCRIPTOR = _INPUTOPTION,
  __module__ = 'karps.proto.io_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.InputOption)
  ))
_sym_db.RegisterMessage(InputOption)


# @@protoc_insertion_point(module_scope)
