# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karps/proto/row.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karps.proto import types_pb2 as karps_dot_proto_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karps/proto/row.proto',
  package='karps.core',
  syntax='proto3',
  serialized_pb=_b('\n\x15karps/proto/row.proto\x12\nkarps.core\x1a\x17karps/proto/types.proto\"\xc3\x01\n\x04\x43\x65ll\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x06 \x01(\x08H\x00\x12,\n\x0b\x61rray_value\x18\n \x01(\x0b\x32\x15.karps.core.ArrayCellH\x00\x12\'\n\x0cstruct_value\x18\x0b \x01(\x0b\x32\x0f.karps.core.RowH\x00\x42\t\n\x07\x65lement\"-\n\tArrayCell\x12 \n\x06values\x18\x01 \x03(\x0b\x32\x10.karps.core.Cell\"\'\n\x03Row\x12 \n\x06values\x18\x01 \x03(\x0b\x32\x10.karps.core.Cell\"V\n\x0c\x43\x65llWithType\x12\x1e\n\x04\x63\x65ll\x18\x01 \x01(\x0b\x32\x10.karps.core.Cell\x12&\n\tcell_type\x18\x02 \x01(\x0b\x32\x13.karps.core.SQLTypeb\x06proto3')
  ,
  dependencies=[karps_dot_proto_dot_types__pb2.DESCRIPTOR,])




_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='karps.core.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_value', full_name='karps.core.Cell.int_value', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='karps.core.Cell.string_value', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='karps.core.Cell.double_value', index=2,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='karps.core.Cell.bool_value', index=3,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='array_value', full_name='karps.core.Cell.array_value', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='struct_value', full_name='karps.core.Cell.struct_value', index=5,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='element', full_name='karps.core.Cell.element',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=63,
  serialized_end=258,
)


_ARRAYCELL = _descriptor.Descriptor(
  name='ArrayCell',
  full_name='karps.core.ArrayCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='karps.core.ArrayCell.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=305,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='karps.core.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='karps.core.Row.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=346,
)


_CELLWITHTYPE = _descriptor.Descriptor(
  name='CellWithType',
  full_name='karps.core.CellWithType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell', full_name='karps.core.CellWithType.cell', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cell_type', full_name='karps.core.CellWithType.cell_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=434,
)

_CELL.fields_by_name['array_value'].message_type = _ARRAYCELL
_CELL.fields_by_name['struct_value'].message_type = _ROW
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['int_value'])
_CELL.fields_by_name['int_value'].containing_oneof = _CELL.oneofs_by_name['element']
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['string_value'])
_CELL.fields_by_name['string_value'].containing_oneof = _CELL.oneofs_by_name['element']
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['double_value'])
_CELL.fields_by_name['double_value'].containing_oneof = _CELL.oneofs_by_name['element']
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['bool_value'])
_CELL.fields_by_name['bool_value'].containing_oneof = _CELL.oneofs_by_name['element']
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['array_value'])
_CELL.fields_by_name['array_value'].containing_oneof = _CELL.oneofs_by_name['element']
_CELL.oneofs_by_name['element'].fields.append(
  _CELL.fields_by_name['struct_value'])
_CELL.fields_by_name['struct_value'].containing_oneof = _CELL.oneofs_by_name['element']
_ARRAYCELL.fields_by_name['values'].message_type = _CELL
_ROW.fields_by_name['values'].message_type = _CELL
_CELLWITHTYPE.fields_by_name['cell'].message_type = _CELL
_CELLWITHTYPE.fields_by_name['cell_type'].message_type = karps_dot_proto_dot_types__pb2._SQLTYPE
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['ArrayCell'] = _ARRAYCELL
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['CellWithType'] = _CELLWITHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), dict(
  DESCRIPTOR = _CELL,
  __module__ = 'karps.proto.row_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.Cell)
  ))
_sym_db.RegisterMessage(Cell)

ArrayCell = _reflection.GeneratedProtocolMessageType('ArrayCell', (_message.Message,), dict(
  DESCRIPTOR = _ARRAYCELL,
  __module__ = 'karps.proto.row_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ArrayCell)
  ))
_sym_db.RegisterMessage(ArrayCell)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'karps.proto.row_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.Row)
  ))
_sym_db.RegisterMessage(Row)

CellWithType = _reflection.GeneratedProtocolMessageType('CellWithType', (_message.Message,), dict(
  DESCRIPTOR = _CELLWITHTYPE,
  __module__ = 'karps.proto.row_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CellWithType)
  ))
_sym_db.RegisterMessage(CellWithType)


# @@protoc_insertion_point(module_scope)
