# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from karps.proto import interface_pb2 as karps_dot_proto_dot_interface__pb2


class KarpsMainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSession = channel.unary_unary(
        '/karps.core.KarpsMain/CreateSession',
        request_serializer=karps_dot_proto_dot_interface__pb2.CreateSessionRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.CreateSessionResponse.FromString,
        )
    self.StreamCreateComputation = channel.unary_stream(
        '/karps.core.KarpsMain/StreamCreateComputation',
        request_serializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.ComputationStreamResponse.FromString,
        )


class KarpsMainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamCreateComputation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KarpsMainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSession': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSession,
          request_deserializer=karps_dot_proto_dot_interface__pb2.CreateSessionRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.CreateSessionResponse.SerializeToString,
      ),
      'StreamCreateComputation': grpc.unary_stream_rpc_method_handler(
          servicer.StreamCreateComputation,
          request_deserializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.ComputationStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'karps.core.KarpsMain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
