# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karps/proto/profiling.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karps.proto import graph_pb2 as karps_dot_proto_dot_graph__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karps/proto/profiling.proto',
  package='karps.core',
  syntax='proto3',
  serialized_pb=_b('\n\x1bkarps/proto/profiling.proto\x12\nkarps.core\x1a\x17karps/proto/graph.proto\"\x1b\n\x19NodeComputationBeginEvent\"\x19\n\x17NodeComputationEndEvent\"\xdc\x01\n\x14NodeComputationEvent\x12$\n\nlocal_path\x18\x01 \x01(\x0b\x32\x10.karps.core.Path\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x42\n\x11\x62\x65gin_computation\x18\x03 \x01(\x0b\x32%.karps.core.NodeComputationBeginEventH\x00\x12>\n\x0f\x65nd_computation\x18\x04 \x01(\x0b\x32#.karps.core.NodeComputationEndEventH\x00\x42\x07\n\x05\x65vent\"R\n\x10\x43hromeTraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ph\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x03\x12\x0b\n\x03pid\x18\x04 \x01(\t\x12\x0b\n\x03tid\x18\x05 \x01(\t\"\x85\x01\n\x10\x43omputationTrace\x12\x33\n\rchrome_events\x18\x01 \x03(\x0b\x32\x1c.karps.core.ChromeTraceEvent\x12<\n\x12\x63omputation_events\x18\x02 \x03(\x0b\x32 .karps.core.NodeComputationEventb\x06proto3')
  ,
  dependencies=[karps_dot_proto_dot_graph__pb2.DESCRIPTOR,])




_NODECOMPUTATIONBEGINEVENT = _descriptor.Descriptor(
  name='NodeComputationBeginEvent',
  full_name='karps.core.NodeComputationBeginEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=95,
)


_NODECOMPUTATIONENDEVENT = _descriptor.Descriptor(
  name='NodeComputationEndEvent',
  full_name='karps.core.NodeComputationEndEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=122,
)


_NODECOMPUTATIONEVENT = _descriptor.Descriptor(
  name='NodeComputationEvent',
  full_name='karps.core.NodeComputationEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_path', full_name='karps.core.NodeComputationEvent.local_path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='karps.core.NodeComputationEvent.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='begin_computation', full_name='karps.core.NodeComputationEvent.begin_computation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_computation', full_name='karps.core.NodeComputationEvent.end_computation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='karps.core.NodeComputationEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=125,
  serialized_end=345,
)


_CHROMETRACEEVENT = _descriptor.Descriptor(
  name='ChromeTraceEvent',
  full_name='karps.core.ChromeTraceEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='karps.core.ChromeTraceEvent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ph', full_name='karps.core.ChromeTraceEvent.ph', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='karps.core.ChromeTraceEvent.ts', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='karps.core.ChromeTraceEvent.pid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tid', full_name='karps.core.ChromeTraceEvent.tid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=429,
)


_COMPUTATIONTRACE = _descriptor.Descriptor(
  name='ComputationTrace',
  full_name='karps.core.ComputationTrace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chrome_events', full_name='karps.core.ComputationTrace.chrome_events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computation_events', full_name='karps.core.ComputationTrace.computation_events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=565,
)

_NODECOMPUTATIONEVENT.fields_by_name['local_path'].message_type = karps_dot_proto_dot_graph__pb2._PATH
_NODECOMPUTATIONEVENT.fields_by_name['begin_computation'].message_type = _NODECOMPUTATIONBEGINEVENT
_NODECOMPUTATIONEVENT.fields_by_name['end_computation'].message_type = _NODECOMPUTATIONENDEVENT
_NODECOMPUTATIONEVENT.oneofs_by_name['event'].fields.append(
  _NODECOMPUTATIONEVENT.fields_by_name['begin_computation'])
_NODECOMPUTATIONEVENT.fields_by_name['begin_computation'].containing_oneof = _NODECOMPUTATIONEVENT.oneofs_by_name['event']
_NODECOMPUTATIONEVENT.oneofs_by_name['event'].fields.append(
  _NODECOMPUTATIONEVENT.fields_by_name['end_computation'])
_NODECOMPUTATIONEVENT.fields_by_name['end_computation'].containing_oneof = _NODECOMPUTATIONEVENT.oneofs_by_name['event']
_COMPUTATIONTRACE.fields_by_name['chrome_events'].message_type = _CHROMETRACEEVENT
_COMPUTATIONTRACE.fields_by_name['computation_events'].message_type = _NODECOMPUTATIONEVENT
DESCRIPTOR.message_types_by_name['NodeComputationBeginEvent'] = _NODECOMPUTATIONBEGINEVENT
DESCRIPTOR.message_types_by_name['NodeComputationEndEvent'] = _NODECOMPUTATIONENDEVENT
DESCRIPTOR.message_types_by_name['NodeComputationEvent'] = _NODECOMPUTATIONEVENT
DESCRIPTOR.message_types_by_name['ChromeTraceEvent'] = _CHROMETRACEEVENT
DESCRIPTOR.message_types_by_name['ComputationTrace'] = _COMPUTATIONTRACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeComputationBeginEvent = _reflection.GeneratedProtocolMessageType('NodeComputationBeginEvent', (_message.Message,), dict(
  DESCRIPTOR = _NODECOMPUTATIONBEGINEVENT,
  __module__ = 'karps.proto.profiling_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.NodeComputationBeginEvent)
  ))
_sym_db.RegisterMessage(NodeComputationBeginEvent)

NodeComputationEndEvent = _reflection.GeneratedProtocolMessageType('NodeComputationEndEvent', (_message.Message,), dict(
  DESCRIPTOR = _NODECOMPUTATIONENDEVENT,
  __module__ = 'karps.proto.profiling_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.NodeComputationEndEvent)
  ))
_sym_db.RegisterMessage(NodeComputationEndEvent)

NodeComputationEvent = _reflection.GeneratedProtocolMessageType('NodeComputationEvent', (_message.Message,), dict(
  DESCRIPTOR = _NODECOMPUTATIONEVENT,
  __module__ = 'karps.proto.profiling_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.NodeComputationEvent)
  ))
_sym_db.RegisterMessage(NodeComputationEvent)

ChromeTraceEvent = _reflection.GeneratedProtocolMessageType('ChromeTraceEvent', (_message.Message,), dict(
  DESCRIPTOR = _CHROMETRACEEVENT,
  __module__ = 'karps.proto.profiling_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ChromeTraceEvent)
  ))
_sym_db.RegisterMessage(ChromeTraceEvent)

ComputationTrace = _reflection.GeneratedProtocolMessageType('ComputationTrace', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONTRACE,
  __module__ = 'karps.proto.profiling_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ComputationTrace)
  ))
_sym_db.RegisterMessage(ComputationTrace)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
