# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karps/proto/interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karps.proto import graph_pb2 as karps_dot_proto_dot_graph__pb2
from karps.proto import io_pb2 as karps_dot_proto_dot_io__pb2
from karps.proto import computation_pb2 as karps_dot_proto_dot_computation__pb2
from karps.proto import profiling_pb2 as karps_dot_proto_dot_profiling__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karps/proto/interface.proto',
  package='karps.core',
  syntax='proto3',
  serialized_pb=_b('\n\x1bkarps/proto/interface.proto\x12\nkarps.core\x1a\x17karps/proto/graph.proto\x1a\x14karps/proto/io.proto\x1a\x1dkarps/proto/computation.proto\x1a\x1bkarps/proto/profiling.proto\"H\n\x14\x43reateSessionRequest\x12\x30\n\x11requested_session\x18\x01 \x01(\x0b\x32\x15.karps.core.SessionId\"\x17\n\x15\x43reateSessionResponse\"\xc9\x01\n\x18\x43reateComputationRequest\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.karps.core.SessionId\x12 \n\x05graph\x18\x03 \x01(\x0b\x32\x11.karps.core.Graph\x12\x38\n\x15requested_computation\x18\x04 \x01(\x0b\x32\x19.karps.core.ComputationId\x12)\n\x0frequested_paths\x18\x05 \x03(\x0b\x32\x10.karps.core.Path\"\x1b\n\x19\x43reateComputationResponse\"\x9d\x01\n\x18\x43omputationStatusRequest\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.karps.core.SessionId\x12.\n\x0b\x63omputation\x18\x02 \x01(\x0b\x32\x19.karps.core.ComputationId\x12)\n\x0frequested_paths\x18\x03 \x03(\x0b\x32\x10.karps.core.Path\"\xed\x02\n\x19\x43omputationStreamResponse\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.karps.core.SessionId\x12.\n\x0b\x63omputation\x18\x02 \x01(\x0b\x32\x19.karps.core.ComputationId\x12&\n\x0bstart_graph\x18\x03 \x01(\x0b\x32\x11.karps.core.Graph\x12\'\n\x0cpinned_graph\x18\x04 \x01(\x0b\x32\x11.karps.core.Graph\x12\x33\n\x07results\x18\x05 \x01(\x0b\x32\".karps.core.BatchComputationResult\x12\x39\n\x12\x63ompilation_result\x18\x06 \x01(\x0b\x32\x1d.karps.core.CompilationResult\x12\x37\n\x11\x63omputation_trace\x18\x07 \x01(\x0b\x32\x1c.karps.core.ComputationTrace\"`\n\x11\x43ompilationResult\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12<\n\x11\x63ompilation_graph\x18\x02 \x03(\x0b\x32!.karps.core.CompilationPhaseGraph2\xcb\x01\n\tKarpsMain\x12T\n\rCreateSession\x12 .karps.core.CreateSessionRequest\x1a!.karps.core.CreateSessionResponse\x12h\n\x17StreamCreateComputation\x12$.karps.core.CreateComputationRequest\x1a%.karps.core.ComputationStreamResponse0\x01\x62\x06proto3')
  ,
  dependencies=[karps_dot_proto_dot_graph__pb2.DESCRIPTOR,karps_dot_proto_dot_io__pb2.DESCRIPTOR,karps_dot_proto_dot_computation__pb2.DESCRIPTOR,karps_dot_proto_dot_profiling__pb2.DESCRIPTOR,])




_CREATESESSIONREQUEST = _descriptor.Descriptor(
  name='CreateSessionRequest',
  full_name='karps.core.CreateSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requested_session', full_name='karps.core.CreateSessionRequest.requested_session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=222,
)


_CREATESESSIONRESPONSE = _descriptor.Descriptor(
  name='CreateSessionResponse',
  full_name='karps.core.CreateSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=247,
)


_CREATECOMPUTATIONREQUEST = _descriptor.Descriptor(
  name='CreateComputationRequest',
  full_name='karps.core.CreateComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='karps.core.CreateComputationRequest.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graph', full_name='karps.core.CreateComputationRequest.graph', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requested_computation', full_name='karps.core.CreateComputationRequest.requested_computation', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requested_paths', full_name='karps.core.CreateComputationRequest.requested_paths', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=451,
)


_CREATECOMPUTATIONRESPONSE = _descriptor.Descriptor(
  name='CreateComputationResponse',
  full_name='karps.core.CreateComputationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=480,
)


_COMPUTATIONSTATUSREQUEST = _descriptor.Descriptor(
  name='ComputationStatusRequest',
  full_name='karps.core.ComputationStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='karps.core.ComputationStatusRequest.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computation', full_name='karps.core.ComputationStatusRequest.computation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requested_paths', full_name='karps.core.ComputationStatusRequest.requested_paths', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=640,
)


_COMPUTATIONSTREAMRESPONSE = _descriptor.Descriptor(
  name='ComputationStreamResponse',
  full_name='karps.core.ComputationStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='karps.core.ComputationStreamResponse.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computation', full_name='karps.core.ComputationStreamResponse.computation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_graph', full_name='karps.core.ComputationStreamResponse.start_graph', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pinned_graph', full_name='karps.core.ComputationStreamResponse.pinned_graph', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='results', full_name='karps.core.ComputationStreamResponse.results', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compilation_result', full_name='karps.core.ComputationStreamResponse.compilation_result', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computation_trace', full_name='karps.core.ComputationStreamResponse.computation_trace', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=1008,
)


_COMPILATIONRESULT = _descriptor.Descriptor(
  name='CompilationResult',
  full_name='karps.core.CompilationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='karps.core.CompilationResult.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compilation_graph', full_name='karps.core.CompilationResult.compilation_graph', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1010,
  serialized_end=1106,
)

_CREATESESSIONREQUEST.fields_by_name['requested_session'].message_type = karps_dot_proto_dot_computation__pb2._SESSIONID
_CREATECOMPUTATIONREQUEST.fields_by_name['session'].message_type = karps_dot_proto_dot_computation__pb2._SESSIONID
_CREATECOMPUTATIONREQUEST.fields_by_name['graph'].message_type = karps_dot_proto_dot_graph__pb2._GRAPH
_CREATECOMPUTATIONREQUEST.fields_by_name['requested_computation'].message_type = karps_dot_proto_dot_computation__pb2._COMPUTATIONID
_CREATECOMPUTATIONREQUEST.fields_by_name['requested_paths'].message_type = karps_dot_proto_dot_graph__pb2._PATH
_COMPUTATIONSTATUSREQUEST.fields_by_name['session'].message_type = karps_dot_proto_dot_computation__pb2._SESSIONID
_COMPUTATIONSTATUSREQUEST.fields_by_name['computation'].message_type = karps_dot_proto_dot_computation__pb2._COMPUTATIONID
_COMPUTATIONSTATUSREQUEST.fields_by_name['requested_paths'].message_type = karps_dot_proto_dot_graph__pb2._PATH
_COMPUTATIONSTREAMRESPONSE.fields_by_name['session'].message_type = karps_dot_proto_dot_computation__pb2._SESSIONID
_COMPUTATIONSTREAMRESPONSE.fields_by_name['computation'].message_type = karps_dot_proto_dot_computation__pb2._COMPUTATIONID
_COMPUTATIONSTREAMRESPONSE.fields_by_name['start_graph'].message_type = karps_dot_proto_dot_graph__pb2._GRAPH
_COMPUTATIONSTREAMRESPONSE.fields_by_name['pinned_graph'].message_type = karps_dot_proto_dot_graph__pb2._GRAPH
_COMPUTATIONSTREAMRESPONSE.fields_by_name['results'].message_type = karps_dot_proto_dot_computation__pb2._BATCHCOMPUTATIONRESULT
_COMPUTATIONSTREAMRESPONSE.fields_by_name['compilation_result'].message_type = _COMPILATIONRESULT
_COMPUTATIONSTREAMRESPONSE.fields_by_name['computation_trace'].message_type = karps_dot_proto_dot_profiling__pb2._COMPUTATIONTRACE
_COMPILATIONRESULT.fields_by_name['compilation_graph'].message_type = karps_dot_proto_dot_graph__pb2._COMPILATIONPHASEGRAPH
DESCRIPTOR.message_types_by_name['CreateSessionRequest'] = _CREATESESSIONREQUEST
DESCRIPTOR.message_types_by_name['CreateSessionResponse'] = _CREATESESSIONRESPONSE
DESCRIPTOR.message_types_by_name['CreateComputationRequest'] = _CREATECOMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['CreateComputationResponse'] = _CREATECOMPUTATIONRESPONSE
DESCRIPTOR.message_types_by_name['ComputationStatusRequest'] = _COMPUTATIONSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ComputationStreamResponse'] = _COMPUTATIONSTREAMRESPONSE
DESCRIPTOR.message_types_by_name['CompilationResult'] = _COMPILATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSessionRequest = _reflection.GeneratedProtocolMessageType('CreateSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATESESSIONREQUEST,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CreateSessionRequest)
  ))
_sym_db.RegisterMessage(CreateSessionRequest)

CreateSessionResponse = _reflection.GeneratedProtocolMessageType('CreateSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATESESSIONRESPONSE,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CreateSessionResponse)
  ))
_sym_db.RegisterMessage(CreateSessionResponse)

CreateComputationRequest = _reflection.GeneratedProtocolMessageType('CreateComputationRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECOMPUTATIONREQUEST,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CreateComputationRequest)
  ))
_sym_db.RegisterMessage(CreateComputationRequest)

CreateComputationResponse = _reflection.GeneratedProtocolMessageType('CreateComputationResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECOMPUTATIONRESPONSE,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CreateComputationResponse)
  ))
_sym_db.RegisterMessage(CreateComputationResponse)

ComputationStatusRequest = _reflection.GeneratedProtocolMessageType('ComputationStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONSTATUSREQUEST,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ComputationStatusRequest)
  ))
_sym_db.RegisterMessage(ComputationStatusRequest)

ComputationStreamResponse = _reflection.GeneratedProtocolMessageType('ComputationStreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONSTREAMRESPONSE,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.ComputationStreamResponse)
  ))
_sym_db.RegisterMessage(ComputationStreamResponse)

CompilationResult = _reflection.GeneratedProtocolMessageType('CompilationResult', (_message.Message,), dict(
  DESCRIPTOR = _COMPILATIONRESULT,
  __module__ = 'karps.proto.interface_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.CompilationResult)
  ))
_sym_db.RegisterMessage(CompilationResult)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class KarpsMainStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateSession = channel.unary_unary(
          '/karps.core.KarpsMain/CreateSession',
          request_serializer=CreateSessionRequest.SerializeToString,
          response_deserializer=CreateSessionResponse.FromString,
          )
      self.StreamCreateComputation = channel.unary_stream(
          '/karps.core.KarpsMain/StreamCreateComputation',
          request_serializer=CreateComputationRequest.SerializeToString,
          response_deserializer=ComputationStreamResponse.FromString,
          )


  class KarpsMainServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def CreateSession(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StreamCreateComputation(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_KarpsMainServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateSession': grpc.unary_unary_rpc_method_handler(
            servicer.CreateSession,
            request_deserializer=CreateSessionRequest.FromString,
            response_serializer=CreateSessionResponse.SerializeToString,
        ),
        'StreamCreateComputation': grpc.unary_stream_rpc_method_handler(
            servicer.StreamCreateComputation,
            request_deserializer=CreateComputationRequest.FromString,
            response_serializer=ComputationStreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'karps.core.KarpsMain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaKarpsMainServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateSession(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StreamCreateComputation(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaKarpsMainStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateSession(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    CreateSession.future = None
    def StreamCreateComputation(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_KarpsMain_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('karps.core.KarpsMain', 'CreateSession'): CreateSessionRequest.FromString,
      ('karps.core.KarpsMain', 'StreamCreateComputation'): CreateComputationRequest.FromString,
    }
    response_serializers = {
      ('karps.core.KarpsMain', 'CreateSession'): CreateSessionResponse.SerializeToString,
      ('karps.core.KarpsMain', 'StreamCreateComputation'): ComputationStreamResponse.SerializeToString,
    }
    method_implementations = {
      ('karps.core.KarpsMain', 'CreateSession'): face_utilities.unary_unary_inline(servicer.CreateSession),
      ('karps.core.KarpsMain', 'StreamCreateComputation'): face_utilities.unary_stream_inline(servicer.StreamCreateComputation),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_KarpsMain_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('karps.core.KarpsMain', 'CreateSession'): CreateSessionRequest.SerializeToString,
      ('karps.core.KarpsMain', 'StreamCreateComputation'): CreateComputationRequest.SerializeToString,
    }
    response_deserializers = {
      ('karps.core.KarpsMain', 'CreateSession'): CreateSessionResponse.FromString,
      ('karps.core.KarpsMain', 'StreamCreateComputation'): ComputationStreamResponse.FromString,
    }
    cardinalities = {
      'CreateSession': cardinality.Cardinality.UNARY_UNARY,
      'StreamCreateComputation': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'karps.core.KarpsMain', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
